<div class="container">
  <footer class="py-5 my-5 border-top">
    <div class="row">
        <div class="col-lg-2 col-md-2 col-sm-2"></div>
      <div class="col-lg-2 col-md-2 col-sm-2">
        <h5>교회소개</h5>
        <ul class="nav flex-column">
          <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-muted">인사말</a></li>
          <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-muted">시설물</a></li>
          <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-muted">연혁</a></li>
          <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-muted">오시는길</a></li>
        </ul>
      </div>

      <div class="col-lg-2 col-md-2 col-sm-2">
        <h5>예배안내</h5>
        <ul class="nav flex-column">
          <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-muted">예배시간</a></li>
          <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-muted">운행시간</a></li>
        </ul>
      </div>

      <div class="col-lg-2 col-md-2 col-sm-2">
        <h5>말씀</h5>
        <ul class="nav flex-column">
          <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-muted">2021년 이후 말씀</a></li>
          <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-muted">2020년 이전 말씀</a></li>
        </ul>
      </div>
      
      <div class="col-lg-2 col-md-2 col-sm-2">
        <h5>교회소식</h5>
        <ul class="nav flex-column">
          <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-muted">공지사항</a></li>
          <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-muted">특별성회</a></li>
        </ul>
      </div>
    </div>

    <div class="mgt20 pdt20 border-top">
        <p>
            정옥용목사 / 경기도 광주시 광남동 목동길69<br>
            (031) 767-9480 / 팩스 (031) 767-9481<br>
            webmaster@sky0808.net
        </p>
    </div>
    
    <div class="d-flex justify-content-center py-4 my-4 border-top">
        <p>Copyright &copy; 하늘문교회기도원 All Rights Reserved. Designed by DreamWebs</p>
      </div>
  </footer>
</div>

</body>
</html>